#!/usr/bin/env bun
import { $ } from "bun"
import pkg from "../package.json"
import { Script } from "@opencode-ai/script"
import { fileURLToPath } from "url"

const dir = fileURLToPath(new URL("..", import.meta.url))
process.chdir(dir)

async function published(name: string, version: string) {
  return (await $`npm view ${name}@${version} version`.nothrow()).exitCode === 0
}

async function publish(dir: string, name: string, version: string) {
  // GitHub artifact downloads can drop the executable bit, and Docker uses the
  // unpacked dist binaries directly rather than the published tarball.
  if (process.platform !== "win32") await $`chmod -R 755 .`.cwd(dir)
  if (await published(name, version)) {
    console.log(`already published ${name}@${version}`)
    return
  }
  await $`bun pm pack`.cwd(dir)
  await $`npm publish *.tgz --access public --tag ${Script.channel}`.cwd(dir)
}

const binaries: Record<string, string> = {}
// binaries live at dist/@bolt-builder/bolt-cli-<os>-<arch>/package.json (scoped, two levels deep)
for (const filepath of new Bun.Glob("**/package.json").scanSync({ cwd: "./dist" })) {
  const pkg = await Bun.file(`./dist/${filepath}`).json()
  binaries[pkg.name] = pkg.version
}
console.log("binaries", binaries)
const version = Object.values(binaries)[0]

// the installed command is `bolt`; the meta package publishes under the scoped repo name
const command = "bolt"
await $`mkdir -p ./dist/${pkg.name}`
await $`mkdir -p ./dist/${pkg.name}/bin`
await $`cp ./script/postinstall.mjs ./dist/${pkg.name}/postinstall.mjs`
await Bun.file(`./dist/${pkg.name}/LICENSE`).write(await Bun.file("../../LICENSE").text())
await Bun.file(`./dist/${pkg.name}/bin/${command}.exe`).write(
  [
    `echo "Error: ${pkg.name}'s postinstall script was not run." >&2`,
    'echo "" >&2',
    'echo "This occurs when using --ignore-scripts during installation, or when using a" >&2',
    'echo "package manager like pnpm that does not run postinstall scripts by default." >&2',
    'echo "" >&2',
    'echo "To fix this, run the postinstall script manually:" >&2',
    `echo "  cd node_modules/${pkg.name} && node postinstall.mjs" >&2`,
    'echo "" >&2',
    `echo "Or reinstall ${pkg.name} without the --ignore-scripts flag." >&2`,
    "exit 1",
    "",
  ].join("\n"),
)

await Bun.file(`./dist/${pkg.name}/package.json`).write(
  JSON.stringify(
    {
      name: pkg.name,
      bin: {
        [command]: `./bin/${command}.exe`,
      },
      scripts: {
        postinstall: "node ./postinstall.mjs",
      },
      version: version,
      license: pkg.license,
      os: ["darwin", "linux", "win32"],
      cpu: ["arm64", "x64"],
      optionalDependencies: binaries,
    },
    null,
    2,
  ),
)

const tasks = Object.entries(binaries).map(async ([name]) => {
  await publish(`./dist/${name}`, name, binaries[name])
})
await Promise.all(tasks)
await publish(`./dist/${pkg.name}`, pkg.name, version)

const image = "ghcr.io/bolt-builder/bolt-cli"
const platforms = "linux/amd64,linux/arm64"
const tags = [`${image}:${version}`, `${image}:${Script.channel}`]
const tagFlags = tags.flatMap((t) => ["-t", t])

// registries
// AUR publishing was removed: the old block targeted upstream's `opencode-bin`
// AUR package, which Bolt does not own. Restore from git history once Bolt has
// its own AUR package.
if (!Script.preview) {
  await $`docker buildx build --platform ${platforms} ${tagFlags} --push .`
  await brew()
}

// Regenerates the Homebrew formula in bolt-builder/homebrew-tap so
// `brew install bolt-builder/tap/bolt-cli` tracks the latest release. The
// sha256 inputs are the exact release assets users download, fetched from the
// (still draft) GitHub release rather than rebuilt locally.
async function brew() {
  const token = process.env.HOMEBREW_TAP_TOKEN
  if (!token) {
    console.warn("HOMEBREW_TAP_TOKEN is not set; skipping homebrew tap update")
    return
  }

  const assets = [
    "bolt-cli-darwin-arm64.zip",
    "bolt-cli-darwin-x64.zip",
    "bolt-cli-linux-arm64.tar.gz",
    "bolt-cli-linux-x64.tar.gz",
  ]
  await $`rm -rf ./dist/brew`
  await $`mkdir -p ./dist/brew`
  await $`gh release download v${Script.version} --repo bolt-builder/bolt-cli --dir ./dist/brew ${assets.flatMap((a) => ["-p", a])}`
  const sha = async (asset: string) => (await $`sha256sum ./dist/brew/${asset} | cut -d' ' -f1`.text()).trim()

  const url = (asset: string) =>
    `https://github.com/bolt-builder/bolt-cli/releases/download/v${Script.version}/${asset}`
  const block = async (asset: string) =>
    [
      `      url "${url(asset)}"`,
      `      sha256 "${await sha(asset)}"`,
      "",
      "      def install",
      '        bin.install "bolt"',
      "      end",
    ].join("\n")

  const formula = [
    "# typed: false",
    "# frozen_string_literal: true",
    "",
    "# This file is generated by the bolt-cli publish script. DO NOT EDIT.",
    "class BoltCli < Formula",
    '  desc "Bolt: the AI coding agent built for the terminal."',
    '  homepage "https://github.com/bolt-builder/bolt-cli"',
    `  version "${Script.version.split("-")[0]}"`,
    "",
    "  on_macos do",
    "    if Hardware::CPU.arm?",
    await block("bolt-cli-darwin-arm64.zip"),
    "    end",
    "    if Hardware::CPU.intel?",
    await block("bolt-cli-darwin-x64.zip"),
    "    end",
    "  end",
    "",
    "  on_linux do",
    "    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?",
    await block("bolt-cli-linux-arm64.tar.gz"),
    "    end",
    "    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?",
    await block("bolt-cli-linux-x64.tar.gz"),
    "    end",
    "  end",
    "end",
    "",
  ].join("\n")

  const tap = `https://x-access-token:${token}@github.com/bolt-builder/homebrew-tap.git`
  await $`rm -rf ./dist/homebrew-tap`
  await $`git clone ${tap} ./dist/homebrew-tap`
  await $`mkdir -p ./dist/homebrew-tap/Formula`
  await Bun.file("./dist/homebrew-tap/Formula/bolt-cli.rb").write(formula)
  await $`git add Formula/bolt-cli.rb`.cwd("./dist/homebrew-tap")
  if ((await $`git diff --cached --quiet`.cwd("./dist/homebrew-tap").nothrow()).exitCode !== 0) {
    await $`git commit -m "bolt-cli v${Script.version}"`.cwd("./dist/homebrew-tap")
    await $`git push`.cwd("./dist/homebrew-tap")
  }
}
